POST http://localhost:3003/api/blogs
Content-Type: Application/json

{
    "title": "Mualiman kolomaniks paras bolgi",
    "author": "Pena Kaalipelto",
    "url": "http://mualiman-kolomaniks-paras-bolgi.com",
    "likes": 50
}